GET http://localhost:8000/api/v1/options/
Content-Type: application/json

###
GET http://localhost:8000/api/v1/options/?description=ывавыа
Content-Type: application/json

###
GET http://localhost:8000/api/v1/options/?id=1
Content-Type: application/json

###
POST http://localhost:8000/api/v1/options/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer b9ec7df54b01332df917affbea83a0c03aba4b66

{
  "description" : "Нормально",
  "question" : 1,
  "answers" : []
}

###
PATCH http://localhost:8000/api/v1/options/4/
Content-Type: application/json
Authorization: Bearer b9ec7df54b01332df917affbea83a0c03aba4b66

{
 "description" : "Нормальненько"
}

###
DELETE http://localhost:8000/api/v1/options/4/
Content-Type: application/json
Authorization: Bearer b9ec7df54b01332df917affbea83a0c03aba4b66

###